name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libleveldb-dev

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.12.1.0"

      - name: Cache cabal store
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project*') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update package list
        run: cabal update

      - name: Build dependencies
        run: cabal build all --only-dependencies --disable-tests --disable-benchmarks

      - name: Build project
        run: cabal build all --disable-tests --disable-benchmarks

      - name: Run tests
        run: cabal test all --test-show-details=direct
